In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset = pd.read_csv("File.csv")
dataset.head(6)

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,NaN,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11
5,6,David Miller,16.0,16.0,9.0,481.0,94*,68.71,337.0,142.72,0.0,2.0,32.0,23

In [4]:
dataset.isnull().sum()

POS        0
Player     0
Mat        1
Inns       7
NO         7
Runs       2
HS         2
Avg        5
BF         8
SR        19
100        1
50         1
4s         2
6s         0
dtype: int64

In [5]:
dataset.fillna(133).head(6)  #sabai null value vako thau ma esle 133 fill gardinxa.Yo ramro tarika haina

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,133.00,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11
5,6,David Miller,16.0,16.0,9.0,481.0,94*,68.71,337.0,142.72,0.0,2.0,32.0,23

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162 entries, 0 to 161
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   POS     162 non-null    int64
 1   Player  162 non-null    object
 2   Mat     161 non-null    float64
 3   Inns    155 non-null    float64
 4   NO      155 non-null    float64
 5   Runs    160 non-null    float64
 6   HS      160 non-null    object
 7   Avg     157 non-null    object
 8   BF      154 non-null    float64
 9   SR      143 non-null    float64
 10  100     161 non-null    float64
 11  50      161 non-null    float64
 12  4s      160 non-null    float64
 13  6s      162 non-null    int64
dtypes: float64(9), int64(2), object(3)
memory usage: 17.8+ KB

In [7]:
#Backward filling.paxadi bata data fill hunxa
dataset.fillna(method="bfill",axis=1).head(6) 
#yesma hardik pandya ko strike rate na xa so tesko paxadi bata data fill hunxa.paxadi hundreds 0 xa so sr ne 0 vayo

C:\Users\Suchana\AppData\Local\Temp\ipykernel_22932\1473427764.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset.fillna(method="bfill",axis=1).head(6)

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,0.0,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11
5,6,David Miller,16.0,16.0,9.0,481.0,94*,68.71,337.0,142.72,0.0,2.0,32.0,23

In [8]:
#Forward filling.aagadi bata data fill hunxa
dataset.fillna(method="ffill",axis=1).head(6) 
#yesma hardik pandya ko strike rate na xa so tesko agadi bata data fill hunxa.agadi bf 371.0 xa so sr ne 371.0 vayo

C:\Users\Suchana\AppData\Local\Temp\ipykernel_22932\3238225693.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset.fillna(method="ffill",axis=1).head(6)

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,371.0,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11
5,6,David Miller,16.0,16.0,9.0,481.0,94*,68.71,337.0,142.72,0.0,2.0,32.0,23

In [17]:
dataset["SR"].mode()[0]
dataset["SR"].fillna(dataset["SR"].mode()[0],inplace=True)
dataset.head(5)

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,100.00,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11

In [24]:
dataset["Inns"].mode()[0]
dataset["Inns"].fillna(dataset["Inns"].mode()[0],inplace=True)
dataset.tail(10)

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
152,153,Shivam Mavi,6.0,3.0,1.0,3.0,2,1.5,7.0,42.85,0.0,0.0,0.0,0
153,154,Harshit Rana,2.0,2.0,1.0,2.0,2,2,2.0,100.00,0.0,0.0,0.0,0
154,155,Navdeep Saini,2.0,1.0,0.0,2.0,2,2,2.0,100.00,0.0,0.0,0.0,0
155,156,Tristan Stubbs,2.0,2.0,0.0,2.0,2,1,4.0,50.00,0.0,0.0,0.0,0
156,157,Pradeep Sangwan,3.0,1.0,0.0,2.0,2,2,5.0,40.00,0.0,0.0,0.0,0
157,158,Fazalhaq Farooqi,3.0,1.0,1.0,2.0,2*,-,8.0,100.00,0.0,0.0,0.0,0
158,159,Jagadeesha Suchith,5.0,1.0,0.0,2.0,2,1,8.0,25.00,0.0,0.0,0.0,0
159,160,Tim Southee,9.0,5.0,1.0,2.0,1*,0.5,12.0,16.66,0.0,0.0,0.0,0
160,161,Nathan Coulter-Nile,1.0,1.0,1.0,1.0,1*,-,2.0,50.00,0.0,0.0,0.0,0
161,162,Anrich Nortje,6.0,1.0,1.0,1.0,1*,-,6.0,16.66,0.0,1.0,0.0,0

In [25]:
for i in dataset.select_dtypes(include="object").columns:
    dataset[i].fillna(dataset[i].mode()[0],inplace=True)

In [26]:
dataset.isnull().sum()

POS       0
Player    0
Mat       0
Inns      0
NO        0
Runs      0
HS        0
Avg       0
BF        0
SR        0
100       0
50        0
4s        0
6s        0
dtype: int64