In [1]:
import pandas as pd

In [19]:
dict={
    "name" :["Ben Stokes","Phil Salt","Jos Buttler","Rashid khan","Liam Livingston"] 
}
df = pd.DataFrame(dict)
df

              name
0       Ben Stokes
1        Phil Salt
2      Jos Buttler
3      Rashid khan
4  Liam Livingston

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()
df["en_name"]=le.fit_transform(df["name"])

In [22]:
df

              name  en_name
0       Ben Stokes        0
1        Phil Salt        3
2      Jos Buttler        1
3      Rashid khan        4
4  Liam Livingston        2

In [23]:
#lets do it in our working dataset
dataset = pd.read_csv("file.csv")
dataset.head()

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,NaN,0.0,4.0,49.0,12
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11

In [24]:
la=LabelEncoder()
dataset["en_player"]=la.fit_transform(dataset["Player"])
dataset.head()

,POS,Player,Mat,Inns,NO,Runs,HS,Avg,BF,SR,100,50,4s,6s,en_player
0,1,Jos Buttler,17.0,17.0,2.0,863.0,116,57.53,579.0,149.05,4.0,4.0,83.0,45,53
1,2,K L Rahul,15.0,15.0,3.0,616.0,103*,51.33,455.0,135.38,2.0,4.0,45.0,30,55
2,3,Quinton De Kock,15.0,15.0,1.0,508.0,140*,36.29,341.0,148.97,1.0,3.0,47.0,23,98
3,4,Hardik Pandya,15.0,15.0,4.0,487.0,87*,44.27,371.0,NaN,0.0,4.0,49.0,12,40
4,5,Shubman Gill,16.0,16.0,2.0,483.0,96,34.5,365.0,132.32,0.0,4.0,51.0,11,137

In [25]:
dataset1 = pd.read_csv("weather_classification_data.csv")
dataset1.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
lb = LabelEncoder()
dataset1["en_Cloud Cover"]=lb.fit_transform(dataset1["Cloud Cover"])
dataset1.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type,en_Cloud Cover
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy,3
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy,3
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny,0
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny,0
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy,2

In [2]:
import pandas as pd
dict1= {
    "surname":["Stokes","Sharma","Cummins","Smith","Kholi" ]
}
dA=pd.DataFrame(dict1)
dA

   surname
0   Stokes
1   Sharma
2  Cummins
3    Smith
4    Kholi

In [3]:
from sklearn.preprocessing import LabelEncoder

In [7]:
la= LabelEncoder()
dA["en_surname"]=la.fit_transform(dA["surname"])
dA

   surname  en_surname
0   Stokes           4
1   Sharma           2
2  Cummins           0
3    Smith           3
4    Kholi           1