In [44]:
import pandas as pd

In [45]:
dict={
    "size":["s","m","l","xl","xxl","xl","m","l","s"]
}
df = pd.DataFrame(dict)
df.head()

  size
0    s
1    m
2    l
3   xl
4  xxl

In [46]:
# Two dimensional dataset chalxa esma so double [[]] use hunxa
data_order=[["s","m","l","xl","xxl"]]

In [47]:
from sklearn.preprocessing import OrdinalEncoder

In [48]:
ol = OrdinalEncoder(categories = data_order)
df[["en_size"]]=ol.fit_transform(df[["size"]])
df

  size  en_size
0    s      0.0
1    m      1.0
2    l      2.0
3   xl      3.0
4  xxl      4.0
5   xl      3.0
6    m      1.0
7    l      2.0
8    s      0.0

In [49]:
#Using Map Function 
#It will be lot more easier

In [50]:
ord_data= {"s":5,"m":6,"xl":7,"l":8,"xxl":9} #jun jati numbering gare ne hunnxa
df["en_size_map"]=df["size"].map(ord_data)
df

  size  en_size  en_size_map
0    s      0.0            5
1    m      1.0            6
2    l      2.0            8
3   xl      3.0            7
4  xxl      4.0            9
5   xl      3.0            7
6    m      1.0            6
7    l      2.0            8
8    s      0.0            5

In [51]:
#now doing it in big data set

In [52]:
import pandas as pd

In [53]:
dataset = pd.read_csv("weather_classification_data.csv")
dataset.head(2)

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy

In [54]:
data_ord = [["inland","mountain","coastal"]]

In [55]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
oe = OrdinalEncoder(categories = data_ord)
oe.fit(dataset[["Location"]])

OrdinalEncoder(categories=[['inland', 'mountain', 'coastal']])

In [57]:
dataset["en_location"] = oe.transform(dataset[["Location"]])
dataset.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type,en_location
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy,0.0
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy,0.0
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny,1.0
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny,2.0
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy,1.0

In [58]:
#Now from map function

In [59]:
data_ord1 = {"Rainy":0,"Cloudy":1,"Sunny":2,"Snowy":3}

In [60]:
dataset["en_Weather_Type"]=dataset["Weather Type"].map(data_ord1)
dataset.head()

,Temperature,Humidity,Wind Speed,Precipitation (%),Cloud Cover,Atmospheric Pressure,UV Index,Season,Visibility (km),Location,Weather Type,en_location,en_Weather_Type
0,14.0,73,9.5,82.0,partly cloudy,1010.82,2,Winter,3.5,inland,Rainy,0.0,0
1,39.0,96,8.5,71.0,partly cloudy,1011.43,7,Spring,10.0,inland,Cloudy,0.0,1
2,30.0,64,7.0,16.0,clear,1018.72,5,Spring,5.5,mountain,Sunny,1.0,2
3,38.0,83,1.5,82.0,clear,1026.25,7,Spring,1.0,coastal,Sunny,2.0,2
4,27.0,74,17.0,66.0,overcast,990.67,1,Winter,2.5,mountain,Rainy,1.0,0